### ISSUE TITLE
Crash on Ubuntu 16.04 x64 builds - possibly function get_available_locale_names

### ISSUE THREAD

**Issue by BroadcastGames** [chrender/fizmo#4]
A couple variations of fizmo such as SDL2 ran into this crash when just doing --help command line output. The very last line of get_available_locale_names is:

     return (char**)delete_list_and_get_null_terminated_ptrs(result_list)

This segfaults as far as I can tell. I don't know C well enough to understand why, but isolating that one line seems to be the issue.

libtools/src/tools/i18n.c:
https://github.com/chrender/libfizmo/blob/390340a22fdefc093cfda9193131291fcfed8411/src/tools/i18n.c#L1358

Digging into **list.c function delete_list_and_get_null_terminated_ptrs - it seems like the trouble is that a zero-element list is being passed in** and this code is unsafe/crashes in that situation?  This function: https://github.com/chrender/libfizmo/blob/390340a22fdefc093cfda9193131291fcfed8411/src/tools/list.c#L128

**Comment by chrender** [comment]
As I gather this is a follow-up from issue #3 – so this has been solved?

**Comment by BroadcastGames** [comment]
I believe a crash is still lurking in this code path. If I understand correctly, the code asks Linux to give a list of installed locale and if the array returned from Linux is empty the function delete_list_and_get_null_terminated_ptrs crashes.  I would suggest to at least add safety check in situation of empty list param?

As to why it happened when I reported it a few days ago vs today - I was using some different ./configure and git checkout methods and I noticed you updated the sub-modules. I also asked my Ubuntu to rebuild the list of locale since then and maybe that helped? I notice that '--help' output does iterate and show the locale installed?

**Comment by chrender** [comment]
It turned out that there were two issues at hand: First, there was indeed a bug in `delete_list_and_get_null_terminated_ptrs` in case the list to convert was empty. The second issue was that the frontends invoking the `get_available_locale_names` function didn't check if they got at least one locale back. Both are now fixed in 6d294f66dea8de17a180012252276e32d728d070.
